# Generated by Django 6.0.6 on 2026-06-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_tutor', '0003_professorsubjectmapping_studentsubjectmapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsubjectmapping',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentsubjectmapping',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studentsubjectmapping',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubjectmapping',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentsubjectmapping',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='cohort',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='voice_tutor.subjectmaster'),
        ),
        migrations.DeleteModel(
            name='ProfessorSubjectMapping',
        ),
        migrations.DeleteModel(
            name='StudentSubjectMapping',
        ),
    ]
