# Generated by Django 6.0.6 on 2026-07-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_tutor', '0005_userprofile_course_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='source_pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
