# Generated by Django 6.0.6 on 2026-07-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_tutor', '0007_batch_delete_cohort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='subject',
        ),
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role__role_code': 'student'}, related_name='student_batches', to='voice_tutor.userprofile'),
        ),
    ]
