# Generated by Django 6.0.6 on 2026-07-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_tutor', '0009_professorallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorallocation',
            name='assignments',
        ),
        migrations.AddField(
            model_name='assignment',
            name='allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='voice_tutor.professorallocation'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='voice_tutor.topicmaster'),
        ),
    ]
