# Generated by Django 6.0.6 on 2026-07-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_tutor', '0010_remove_professorallocation_assignments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='allocation',
        ),
        migrations.AddField(
            model_name='assignment',
            name='professor_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='voice_tutor.professorallocation'),
        ),
    ]
