# Generated by Django 6.0.7 on 2026-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice_tutor", "0011_remove_assignment_allocation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttopicassessmentreview",
            name="saved_answers",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
