name: Deploy Django to AWS Elastic Beanstalk

on:
  push:
    branches:
      - Main  # Change to 'master' if your default branch is named master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Generate Deployment ZIP
        run: |
          zip -r deploy.zip . -x "*.git*" "venv/*" "__pycache__/*" "*.env"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: insync-backend-app
          environment_name: Insync-backend-app-env
          version_label: "deploy-${{ github.sha }}"
          region: ap-south-1
          deployment_package: deploy.zip